/**
 * <highlights-section> — Business impact metrics grid
 */
import { addComponentCss } from '/js/shared.js'

class HighlightsSection extends HTMLElement {
  connectedCallback() {
    addComponentCss('highlights-section')

    const metrics = [
      { value: '$1.4T', desc: 'AUM managed on SaaS platforms I oversaw',
        context: 'Tamarac' },
      { value: '$1.8B', desc: 'New addressable market unlocked via PCI certification',
        context: 'Foundever via NDR' },
      { value: '$20M', desc: 'New revenue delivered via personally developed AI-powered engagement systems',
        context: 'Kitsap Credit Union' },
      { value: '$16M', desc: 'Revenue generated by enterprise platform in its first year',
        context: 'Crelate' },
      { value: '↓85%', desc: 'Reduction in platform incidents via monitoring redesign',
        context: 'Impact.com via NDR' },
      { value: '↓90%', desc: 'Post-release defect reduction through quality culture',
        context: 'Crelate' },
      { value: '10x',  desc: 'Frontend productivity improvement via modernization',
        context: 'Impact.com via NDR' },
      { value: '$1.4M', desc: 'Cost savings through automation &amp; vendor strategy',
        context: 'Foundever via NDR' },
      { value: '6 mo', desc: 'Pre-seed AI startup to profitability',
        context: 'Revere via NDR' },
    ];

    this.innerHTML = `
      <section id="highlights">
        <div class="section-inner">

          <div class="section-header reveal">
            <div class="section-eyebrow">Business Impact</div>
            <h2 class="section-title">Results That <em>Matter</em></h2>
          </div>

          <p class="highlights-intro reveal">
            I measure success in outcomes, not output. Here are some of the
            headline numbers from my career.
          </p>

          <div class="highlights-grid">
            ${metrics.map(m => this._card(m)).join('')}
          </div>

        </div>
      </section>
    `;
  }

  _card({ value, desc, context }) {
    return `
      <div class="highlight-card reveal">
        <div class="highlight-metric">${value}</div>
        <div class="highlight-desc">${desc}</div>
        <div class="highlight-context">${context}</div>
      </div>
    `;
  }
}

customElements.define('highlights-section', HighlightsSection);
